# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4d55cc55fa99d6584734e84e04efa01"
name = "barbershop-development"
application_url = "https://barbershop--development.gadget.app/api/shopify/install-or-render"
embedded = true
handle = "barbershop-development"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://barbershop--development.gadget.app/api/connections/auth/shopify/callback"
]

[app_proxy]
url = "https://barbershop--development.gadget.app"
subpath = "apps-barbershop"
prefix = "apps"

[pos]
embedded = false
