api_version = "2025-04"

[[extensions]]
uid = "b8af2af5-91ce-56a3-2dd8-974fe772a1a036fcf0d7"
type = "ui_extension"
name = "Appointments"
handle = "pos-ui-smart-grid"
description = "View and manage bookings in POS"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"

