# Site settings
title: "SimplyBook — Shopify Booking App"
description: "SimplyBook is a general‑purpose booking app for Shopify. Perfect for barbershops, salons, personal trainers, and more. Seamless Shopify Checkout and POS integration. $9/month with a 7‑day free trial."
author: "SimplyBook"
email: "hello@shopifybookingapp.com"
url: "https://shopifybookingapp.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme settings
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social media
social:
  name: Barbershop Pro
  links:
    - https://www.youtube.com/barbershoppro
    - https://x.com/barbershoppro

# SEO
seo:
  type: "WebSite"
  name: "SimplyBook"
  description: "General‑purpose booking app for Shopify with Checkout and POS integration."
  url: "https://shopifybookingapp.com"
